// Generated by gencpp from file sensor_fusion/convert_to_quaternion_datatypeResponse.msg
// DO NOT EDIT!


#ifndef SENSOR_FUSION_MESSAGE_CONVERT_TO_QUATERNION_DATATYPERESPONSE_H
#define SENSOR_FUSION_MESSAGE_CONVERT_TO_QUATERNION_DATATYPERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sensor_fusion
{
template <class ContainerAllocator>
struct convert_to_quaternion_datatypeResponse_
{
  typedef convert_to_quaternion_datatypeResponse_<ContainerAllocator> Type;

  convert_to_quaternion_datatypeResponse_()
    : qx(0.0)
    , qy(0.0)
    , qz(0.0)
    , qw(0.0)  {
    }
  convert_to_quaternion_datatypeResponse_(const ContainerAllocator& _alloc)
    : qx(0.0)
    , qy(0.0)
    , qz(0.0)
    , qw(0.0)  {
  (void)_alloc;
    }



   typedef double _qx_type;
  _qx_type qx;

   typedef double _qy_type;
  _qy_type qy;

   typedef double _qz_type;
  _qz_type qz;

   typedef double _qw_type;
  _qw_type qw;





  typedef boost::shared_ptr< ::sensor_fusion::convert_to_quaternion_datatypeResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sensor_fusion::convert_to_quaternion_datatypeResponse_<ContainerAllocator> const> ConstPtr;

}; // struct convert_to_quaternion_datatypeResponse_

typedef ::sensor_fusion::convert_to_quaternion_datatypeResponse_<std::allocator<void> > convert_to_quaternion_datatypeResponse;

typedef boost::shared_ptr< ::sensor_fusion::convert_to_quaternion_datatypeResponse > convert_to_quaternion_datatypeResponsePtr;
typedef boost::shared_ptr< ::sensor_fusion::convert_to_quaternion_datatypeResponse const> convert_to_quaternion_datatypeResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sensor_fusion::convert_to_quaternion_datatypeResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sensor_fusion::convert_to_quaternion_datatypeResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sensor_fusion::convert_to_quaternion_datatypeResponse_<ContainerAllocator1> & lhs, const ::sensor_fusion::convert_to_quaternion_datatypeResponse_<ContainerAllocator2> & rhs)
{
  return lhs.qx == rhs.qx &&
    lhs.qy == rhs.qy &&
    lhs.qz == rhs.qz &&
    lhs.qw == rhs.qw;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sensor_fusion::convert_to_quaternion_datatypeResponse_<ContainerAllocator1> & lhs, const ::sensor_fusion::convert_to_quaternion_datatypeResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sensor_fusion

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::sensor_fusion::convert_to_quaternion_datatypeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sensor_fusion::convert_to_quaternion_datatypeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sensor_fusion::convert_to_quaternion_datatypeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sensor_fusion::convert_to_quaternion_datatypeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensor_fusion::convert_to_quaternion_datatypeResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensor_fusion::convert_to_quaternion_datatypeResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sensor_fusion::convert_to_quaternion_datatypeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6e41723dd8df2efa508384c23a439e4c";
  }

  static const char* value(const ::sensor_fusion::convert_to_quaternion_datatypeResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6e41723dd8df2efaULL;
  static const uint64_t static_value2 = 0x508384c23a439e4cULL;
};

template<class ContainerAllocator>
struct DataType< ::sensor_fusion::convert_to_quaternion_datatypeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensor_fusion/convert_to_quaternion_datatypeResponse";
  }

  static const char* value(const ::sensor_fusion::convert_to_quaternion_datatypeResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sensor_fusion::convert_to_quaternion_datatypeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 qx\n"
"float64 qy\n"
"float64 qz\n"
"float64 qw\n"
;
  }

  static const char* value(const ::sensor_fusion::convert_to_quaternion_datatypeResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sensor_fusion::convert_to_quaternion_datatypeResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.qx);
      stream.next(m.qy);
      stream.next(m.qz);
      stream.next(m.qw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct convert_to_quaternion_datatypeResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sensor_fusion::convert_to_quaternion_datatypeResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sensor_fusion::convert_to_quaternion_datatypeResponse_<ContainerAllocator>& v)
  {
    s << indent << "qx: ";
    Printer<double>::stream(s, indent + "  ", v.qx);
    s << indent << "qy: ";
    Printer<double>::stream(s, indent + "  ", v.qy);
    s << indent << "qz: ";
    Printer<double>::stream(s, indent + "  ", v.qz);
    s << indent << "qw: ";
    Printer<double>::stream(s, indent + "  ", v.qw);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SENSOR_FUSION_MESSAGE_CONVERT_TO_QUATERNION_DATATYPERESPONSE_H
