// Generated by gencpp from file sensor_fusion/convert_to_quaternion_datatype.msg
// DO NOT EDIT!


#ifndef SENSOR_FUSION_MESSAGE_CONVERT_TO_QUATERNION_DATATYPE_H
#define SENSOR_FUSION_MESSAGE_CONVERT_TO_QUATERNION_DATATYPE_H

#include <ros/service_traits.h>


#include <sensor_fusion/convert_to_quaternion_datatypeRequest.h>
#include <sensor_fusion/convert_to_quaternion_datatypeResponse.h>


namespace sensor_fusion
{

struct convert_to_quaternion_datatype
{

typedef convert_to_quaternion_datatypeRequest Request;
typedef convert_to_quaternion_datatypeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct convert_to_quaternion_datatype
} // namespace sensor_fusion


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sensor_fusion::convert_to_quaternion_datatype > {
  static const char* value()
  {
    return "b6b76783e497fcb836668982f5fd5ffd";
  }

  static const char* value(const ::sensor_fusion::convert_to_quaternion_datatype&) { return value(); }
};

template<>
struct DataType< ::sensor_fusion::convert_to_quaternion_datatype > {
  static const char* value()
  {
    return "sensor_fusion/convert_to_quaternion_datatype";
  }

  static const char* value(const ::sensor_fusion::convert_to_quaternion_datatype&) { return value(); }
};


// service_traits::MD5Sum< ::sensor_fusion::convert_to_quaternion_datatypeRequest> should match
// service_traits::MD5Sum< ::sensor_fusion::convert_to_quaternion_datatype >
template<>
struct MD5Sum< ::sensor_fusion::convert_to_quaternion_datatypeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sensor_fusion::convert_to_quaternion_datatype >::value();
  }
  static const char* value(const ::sensor_fusion::convert_to_quaternion_datatypeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sensor_fusion::convert_to_quaternion_datatypeRequest> should match
// service_traits::DataType< ::sensor_fusion::convert_to_quaternion_datatype >
template<>
struct DataType< ::sensor_fusion::convert_to_quaternion_datatypeRequest>
{
  static const char* value()
  {
    return DataType< ::sensor_fusion::convert_to_quaternion_datatype >::value();
  }
  static const char* value(const ::sensor_fusion::convert_to_quaternion_datatypeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sensor_fusion::convert_to_quaternion_datatypeResponse> should match
// service_traits::MD5Sum< ::sensor_fusion::convert_to_quaternion_datatype >
template<>
struct MD5Sum< ::sensor_fusion::convert_to_quaternion_datatypeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sensor_fusion::convert_to_quaternion_datatype >::value();
  }
  static const char* value(const ::sensor_fusion::convert_to_quaternion_datatypeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sensor_fusion::convert_to_quaternion_datatypeResponse> should match
// service_traits::DataType< ::sensor_fusion::convert_to_quaternion_datatype >
template<>
struct DataType< ::sensor_fusion::convert_to_quaternion_datatypeResponse>
{
  static const char* value()
  {
    return DataType< ::sensor_fusion::convert_to_quaternion_datatype >::value();
  }
  static const char* value(const ::sensor_fusion::convert_to_quaternion_datatypeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SENSOR_FUSION_MESSAGE_CONVERT_TO_QUATERNION_DATATYPE_H
