(cl:defpackage sensor_fusion-srv
  (:use )
  (:export
   "CONVERT_TO_QUATERNION_DATATYPE"
   "<CONVERT_TO_QUATERNION_DATATYPE-REQUEST>"
   "CONVERT_TO_QUATERNION_DATATYPE-REQUEST"
   "<CONVERT_TO_QUATERNION_DATATYPE-RESPONSE>"
   "CONVERT_TO_QUATERNION_DATATYPE-RESPONSE"
  ))

